name: test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.filter.outputs.only_templates_md }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            only_templates_md:
              - templates/**/*.md
              - '!**/*.{js,ts,jsx,tsx,json,yml,yaml}'

  test:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - name: Run tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: pnpm test
      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        env:
          VITEST_TEST_TIMEOUT: 60000
        run: pnpm test
      - name: Verify CLI on ${{ matrix.os }}
        run: |
          pnpm link --global
          ffg --help || exit 1 