name: Publish to npm

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      only_templates_md: ${{ steps.filter.outputs.only_templates_md }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            only_templates_md:
              - templates/**/*.md
              - '!**/*.{js,ts,jsx,tsx,json,yml,yaml}'

  release:
    name: Release
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - if: ${{ needs.check_changes.outputs.only_templates_md != 'true' }}
        run: pnpm test
      - name: Verify CLI
        run: |
          pnpm link --global
          ffg --help || exit 1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          pnpm semantic-release
